name: GitHub-Profile-3D-Contrib

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      - name: GitHub-Profile-3D-Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
